### ISSUE TITLE
Unable to Scan European VISA

### ISSUE THREAD

**Issue by moeadham** [triangle-io/applications#2]
Hey Ameen,

I recently tried to scan a VISA in Switzerland with no luck. Can you give us a better idea of what types of cards will function or not? Are there any regional restrictions? 

-Moe

**Comment by ameent** [comment]
Hello Moe,

We support all Visa cards worldwide and have tested our platform with all types of contactless cards in circulation (through test cards provided by Visa). There may be something unique about the card you tried that caused an issue (for example how the card was provisioned using its unique information). What's the exception that is thrown when you try to scan the card?

Thanks,
-Ameen

**Comment by moeadham** [comment]
Hey,

Sorry, I don't have access to the card anymore, but most tests passed
successfully. Is there any instance where a card will not release an
account number? Or is it generally guaranteed.

Thanks,
Moe

**Comment by ameent** [comment]
Hello,

Account numbers are guaranteed. We will always be able to extract it. I'll close the issue for now since we no longer have access to the card. Please do let us know in case you run into any other issues so that we can investigate for you.

Thanks!
-Ameen
